/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecRouteImport } from './routes/spec'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WalkthroughRouteImport } from './routes/walkthrough'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecRoute = SpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkthroughRoute = WalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spec': typeof SpecRoute
  '/studio': typeof StudioRoute
  '/walkthrough': typeof WalkthroughRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spec': typeof SpecRoute
  '/studio': typeof StudioRoute
  '/walkthrough': typeof WalkthroughRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spec': typeof SpecRoute
  '/studio': typeof StudioRoute
  '/walkthrough': typeof WalkthroughRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spec' | '/studio' | '/walkthrough'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spec' | '/studio' | '/walkthrough'
  id: '__root__' | '/' | '/spec' | '/studio' | '/walkthrough'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpecRoute: typeof SpecRoute
  StudioRoute: typeof StudioRoute
  WalkthroughRoute: typeof WalkthroughRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec': {
      id: '/spec'
      path: '/spec'
      fullPath: '/spec'
      preLoaderRoute: typeof SpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walkthrough': {
      id: '/walkthrough'
      path: '/walkthrough'
      fullPath: '/walkthrough'
      preLoaderRoute: typeof WalkthroughRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpecRoute: SpecRoute,
  StudioRoute: StudioRoute,
  WalkthroughRoute: WalkthroughRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
